// AUTO-GENERATED authority map script.
// Usage: npx tsx scripts/generators/generate-authority-map.ts

import fs from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';

import { ensureGraphInitialized, getResolver } from '../../src/domains/init/ensureGraphInitialized';
import { sortByAuthority } from '../../src/lib/authority/authorityScore';
import type { AuthorityItem } from '../../src/lib/authority/resolver';
import { resolveConversionGoal } from '../../src/lib/content-graph/conversionGoals';
import { getStructuredContentGraph } from '../../src/lib/content-graph/registry';
import type { ContentNodeType } from '../../src/lib/content-graph/types';

const root = process.cwd();
const OUTPUT_DIR = path.join(root, 'src', 'lib', 'authority', 'generated');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'authorityMap.ts');
const REPORTS_DIR = path.join(root, 'reports');
const REPORT_FILE = path.join(REPORTS_DIR, 'authority-map.json');

type SlotMap<T> = Record<string, T>;

interface ServiceSlots {
  services: AuthorityItem[];
}
interface FeatureSlots {
  services: AuthorityItem[];
}
interface IndustrySlots {
  services: AuthorityItem[];
  caseStudies: AuthorityItem[];
  resources: AuthorityItem[];
}
interface BlogSlots {
  resources: AuthorityItem[];
  industries: AuthorityItem[];
}
interface ResourceSlots {
  services: AuthorityItem[];
  industries: AuthorityItem[];
}
interface CaseStudySlots {
  industries: AuthorityItem[];
  resources: AuthorityItem[];
}

async function main() {
  await ensureGraphInitialized();

  const structuredGraph = getStructuredContentGraph();

  const resolver = getResolver();
  const {
    getAllRouteSlugs,
    getServiceSlots,
    getFeatureSlots,
    getIndustrySlots,
    getBlogSlots,
    getResourceSlots,
    getCaseStudySlots,
  } = resolver;

  const slugs = getAllRouteSlugs();

  const service: SlotMap<ServiceSlots> = {};
  const feature: SlotMap<FeatureSlots> = {};
  const industry: SlotMap<IndustrySlots> = {};
  const blog: SlotMap<BlogSlots> = {};
  const resource: SlotMap<ResourceSlots> = {};
  const caseStudy: SlotMap<CaseStudySlots> = {};

  for (const slug of slugs.services.sort()) {
    const raw = getServiceSlots(slug);
    service[slug] = { services: sortByAuthority(raw.services) };
  }
  for (const slug of slugs.features.sort()) {
    const raw = getFeatureSlots(slug);
    feature[slug] = { services: sortByAuthority(raw.services) };
  }
  for (const slug of slugs.industries.sort()) {
    const raw = getIndustrySlots(slug);
    industry[slug] = {
      services: sortByAuthority(raw.services),
      caseStudies: sortByAuthority(raw.caseStudies),
      resources: sortByAuthority(raw.resources),
    };
  }
  for (const slug of slugs.blogPosts.sort()) {
    const raw = getBlogSlots(slug);
    blog[slug] = {
      resources: sortByAuthority(raw.resources),
      industries: sortByAuthority(raw.industries),
    };
  }
  for (const slug of slugs.resources.sort()) {
    const raw = getResourceSlots(slug);
    resource[slug] = {
      services: sortByAuthority(raw.services),
      industries: sortByAuthority(raw.industries),
    };
  }
  for (const slug of slugs.caseStudies.sort()) {
    const raw = getCaseStudySlots(slug);
    caseStudy[slug] = {
      industries: sortByAuthority(raw.industries),
      resources: sortByAuthority(raw.resources),
    };
  }

  const map = { service, feature, industry, blog, resource, caseStudy };

  // Build conversion metadata for each page
  const conversionMeta: Record<string, { conversionGoal: string; conversionPriority: number }> = {};
  const typeMap: Record<string, ContentNodeType> = {};
  for (const slug of slugs.services) typeMap[slug] = 'service';
  for (const slug of slugs.features) typeMap[slug] = 'feature';
  for (const slug of slugs.industries) typeMap[slug] = 'industry-detail';
  for (const slug of slugs.blogPosts) typeMap[slug] = 'blog';
  for (const slug of slugs.resources) typeMap[slug] = 'resource';
  for (const slug of slugs.caseStudies) typeMap[slug] = 'case-study';

  for (const [slug, nodeType] of Object.entries(typeMap)) {
    conversionMeta[slug] = resolveConversionGoal(nodeType);
  }

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  const content = [
    '// AUTO-GENERATED by scripts/generators/generate-authority-map.ts — Do not edit manually.',
    '// Regenerate: npx tsx scripts/generators/generate-authority-map.ts',
    '',
    'export interface AuthorityMapItem {',
    '  title: string;',
    '  description: string;',
    '  slug: string;',
    '  path: string;',
    '  nodeType: string;',
    '}',
    '',
    'interface ServiceSlots { services: AuthorityMapItem[] }',
    'interface FeatureSlots { services: AuthorityMapItem[] }',
    'interface IndustrySlots { services: AuthorityMapItem[]; caseStudies: AuthorityMapItem[]; resources: AuthorityMapItem[] }',
    'interface BlogSlots { resources: AuthorityMapItem[]; industries: AuthorityMapItem[] }',
    'interface ResourceSlots { services: AuthorityMapItem[]; industries: AuthorityMapItem[] }',
    'interface CaseStudySlots { industries: AuthorityMapItem[]; resources: AuthorityMapItem[] }',
    '',
    'export interface AuthorityMap {',
    '  service: Record<string, ServiceSlots>;',
    '  feature: Record<string, FeatureSlots>;',
    '  industry: Record<string, IndustrySlots>;',
    '  blog: Record<string, BlogSlots>;',
    '  resource: Record<string, ResourceSlots>;',
    '  caseStudy: Record<string, CaseStudySlots>;',
    '}',
    '',
    `export const AUTHORITY_MAP: AuthorityMap = ${JSON.stringify(map, null, 2)};`,
    '',
    'export interface ConversionMeta {',
    '  conversionGoal: string;',
    '  conversionPriority: number;',
    '}',
    '',
    `export const CONVERSION_META: Record<string, ConversionMeta> = ${JSON.stringify(conversionMeta, null, 2)};`,
    '',
  ].join('\n');

  // Format with prettier so check-generated doesn't see a diff
  const prettierConfig = await prettier.resolveConfig(OUTPUT_FILE);
  const formatted = await prettier.format(content, { ...prettierConfig, filepath: OUTPUT_FILE });
  fs.writeFileSync(OUTPUT_FILE, formatted, 'utf8');

  const authorityReport = {
    generatedAt: new Date().toISOString(),
    nodes: structuredGraph.nodes.map(node => ({
      id: node.id,
      slug: node.slug,
      type: node.type,
      path: node.path,
      systems: node.systems ?? [],
      topics: node.topics ?? [],
      industries: node.industries ?? [],
    })),
    edges: structuredGraph.nodes.flatMap(node => [
      ...(node.relatesTo ?? []).map(edge => ({ source: node.id, target: edge.id, type: 'relatesTo', sourceType: edge.source })),
      ...(node.supports ?? []).map(edge => ({ source: node.id, target: edge.id, type: 'supports', sourceType: edge.source })),
      ...(node.validates ?? []).map(edge => ({ source: node.id, target: edge.id, type: 'validates', sourceType: edge.source })),
    ]),
  };

  fs.mkdirSync(REPORTS_DIR, { recursive: true });
  fs.writeFileSync(REPORT_FILE, JSON.stringify(authorityReport, null, 2) + '\n', 'utf8');

  const stats = {
    services: slugs.services.length,
    features: slugs.features.length,
    industries: slugs.industries.length,
    blogPosts: slugs.blogPosts.length,
    resources: slugs.resources.length,
    caseStudies: slugs.caseStudies.length,
  };
  const total = Object.values(stats).reduce((a, b) => a + b, 0);

  console.log(
    `[authority-map] Generated map for ${total} nodes → ${path.relative(root, OUTPUT_FILE)}`
  );
  console.log(`  report: ${path.relative(root, REPORT_FILE)}`);
  console.log(`  services: ${stats.services}, features: ${stats.features}, industries: ${stats.industries}`);
  console.log(`  blog: ${stats.blogPosts}, resources: ${stats.resources}, caseStudies: ${stats.caseStudies}`);
}

main();
