export const systemKnowledge = {
  validators: [
    'check-generated',
    'typecheck',
    'lint',
    'validate-content-contract',
    'validate-content-quality',
    'validate-domain-structure',
    'validate-cta-label-contract',
    'validate-cta-resolver-integrity',
    'validate-conversion-contract',
    'validate-template-payload-sufficiency',
    'validate-section-structure',
    'validate-section-shell-integrity',
    'validate-design-system',
    'validate-ui-purity',
    'validate-graph',
    'validate-internal-links',
    'validate-cta-violations',
    'validate-related-duplication',
    'validate-production-contracts',
    'validate-inline-link-misuse',
    'generate-proof-coverage',
    'validate-tokens',
    'validate-inline-styles',
    'validate-docs',
    'validate-vocabulary',
  ],
  analyzers: [
    'generate-content-gaps',
    'audit-content-consistency',
    'detect-page-priorities',
    'generate-content-intelligence',
    'inspect-graph',
    'score-content',
  ],
  reports: [
    'validation-report.json',
    'system-report.json',
    'pipeline-report.json',
    'topic-insights.json',
    'graph-derived-summary.json',
    'dashboard/system.json',
    'dashboard/validators.json',
    'dashboard/graph.json',
    'dashboard/topics.json',
    'dashboard/content.json',
    'dashboard/pipeline.json',
  ],
  pipelineSteps: ['validate:all', 'export:reports', 'dashboard-data', 'system-report'],
} as const;
