// AUTO-GENERATED by scripts/generate-content-registries.mjs. Do not edit manually.
import { carDetailingRepeatCustomerDrop } from '@/domains/case-studies/content/CarDetailingRepeatCustomerDrop';
import { cleaningBusinessLeadLoss } from '@/domains/case-studies/content/CleaningBusinessLeadLoss';
import { constructionLeadTrackingChaos } from '@/domains/case-studies/content/ConstructionLeadTrackingChaos';
import { contractorReviewGap } from '@/domains/case-studies/content/ContractorReviewGap';
import { dentalClinicMissedAppointments } from '@/domains/case-studies/content/DentalClinicMissedAppointments';
import { electricianQuoteDelay } from '@/domains/case-studies/content/ElectricianQuoteDelay';
import { realEstateInquiryRouting } from '@/domains/case-studies/content/RealEstateInquiryRouting';
import { realtorLeadFollowUpAutomation } from '@/domains/case-studies/content/RealtorLeadFollowUpAutomation';
import { fitnessStudioTrialDropOff } from '@/domains/case-studies/content/FitnessStudioTrialDropOff';
import { automotiveServiceReminderAutomation } from '@/domains/case-studies/content/AutomotiveServiceReminderAutomation';
import { autoRepairMissedCallRecovery } from '@/domains/case-studies/content/AutoRepairMissedCallRecovery';
import { hvacEmergencyLeadRouting } from '@/domains/case-studies/content/HvacEmergencyLeadRouting';
import { hvacMaintenancePlanReactivation } from '@/domains/case-studies/content/HvacMaintenancePlanReactivation';
import { hvacSeasonalLeadSurgeHandling } from '@/domains/case-studies/content/HvacSeasonalLeadSurgeHandling';
import { lawFirmConsultationBookingSystem } from '@/domains/case-studies/content/LawFirmConsultationBookingSystem';
import { lawFirmClientIntakeAutomation } from '@/domains/case-studies/content/LawFirmClientIntakeAutomation';
import { crmPipelineVisibilityTransformation } from '@/domains/case-studies/content/CrmPipelineVisibilityTransformation';
import { locksmithLateNightMissedLeads } from '@/domains/case-studies/content/LocksmithLateNightMissedLeads';
import { beautySalonManchesterCustom } from '@/domains/case-studies/content/BeautySalonManchesterCustom';
import { pestControlRapidResponseFailure } from '@/domains/case-studies/content/PestControlRapidResponseFailure';
import { plumberEmergencyCallMissed } from '@/domains/case-studies/content/PlumberEmergencyCallMissed';
import { roofingEstimateFollowUpAutomation } from '@/domains/case-studies/content/RoofingEstimateFollowUpAutomation';
import { roofingWebsiteRebuildWithCrm } from '@/domains/case-studies/content/RoofingWebsiteRebuildWithCrm';
import { salonNoShowReductionSystem } from '@/domains/case-studies/content/SalonNoShowReductionSystem';
import { salonReviewGenerationAutomation } from '@/domains/case-studies/content/SalonReviewGenerationAutomation';
import type { CaseStudyData } from '@/domains/case-studies/types';

export const CASE_STUDY_REGISTRY: Record<string, CaseStudyData> = {
  'car-detailing-customers-not-coming-back': carDetailingRepeatCustomerDrop,
  'cleaning-enquiries-half-getting-lost': cleaningBusinessLeadLoss,
  'construction-leads-everywhere-untracked': constructionLeadTrackingChaos,
  'contractor-solid-work-no-reviews': contractorReviewGap,
  'dental-bookings-people-not-showing-up': dentalClinicMissedAppointments,
  'electrician-quote-replies-too-slow': electricianQuoteDelay,
  'estate-agent-enquiries-going-to-the-wrong-place': realEstateInquiryRouting,
  'estate-agent-enquiries-not-becoming-conversations': realtorLeadFollowUpAutomation,
  'fitness-trial-signups-not-coming-back': fitnessStudioTrialDropOff,
  'garage-customers-came-once-then-disappeared': automotiveServiceReminderAutomation,
  'garage-morning-rush-missed-calls': autoRepairMissedCallRecovery,
  'hvac-after-hours-calls-going-cold': hvacEmergencyLeadRouting,
  'hvac-past-customers-not-coming-back': hvacMaintenancePlanReactivation,
  'hvac-peak-season-couldnt-keep-up': hvacSeasonalLeadSurgeHandling,
  'law-firm-consultations-not-becoming-clients': lawFirmConsultationBookingSystem,
  'law-firm-intake-stalled-after-first-enquiry': lawFirmClientIntakeAutomation,
  'leads-everywhere-no-one-knew-what-was-happening': crmPipelineVisibilityTransformation,
  'locksmith-late-night-calls-missed': locksmithLateNightMissedLeads,
  'manchester-salon-steady-clients-growth-stalled': beautySalonManchesterCustom,
  'pest-control-urgent-calls-cant-get-through': pestControlRapidResponseFailure,
  'plumber-emergency-calls-mostly-missed': plumberEmergencyCallMissed,
  'roofing-quotes-not-being-followed-up': roofingEstimateFollowUpAutomation,
  'roofing-website-looked-fine-work-not-flowing': roofingWebsiteRebuildWithCrm,
  'salon-bookings-full-chairs-empty': salonNoShowReductionSystem,
  'salon-great-work-going-unseen': salonReviewGenerationAutomation,
};

export const caseStudies = Object.values(CASE_STUDY_REGISTRY);
