// AUTO-GENERATED by scripts/generate-content-registries.mjs. Do not edit manually.
import { appointmentBusinessBookingAutomation } from '@/domains/case-studies/content/AppointmentBusinessBookingAutomation';
import { appointmentReminderNoShowReduction } from '@/domains/case-studies/content/AppointmentReminderNoShowReduction';
import { autoRepairMissedCallRecovery } from '@/domains/case-studies/content/AutoRepairMissedCallRecovery';
import { automotiveServiceReminderAutomation } from '@/domains/case-studies/content/AutomotiveServiceReminderAutomation';
import { beautySalonManchesterAllSections } from '@/domains/case-studies/content/BeautySalonManchesterAllSections';
import { beautySalonManchesterCustom } from '@/domains/case-studies/content/BeautySalonManchesterCustom';
import { crmPipelineVisibilityTransformation } from '@/domains/case-studies/content/CrmPipelineVisibilityTransformation';
import { hvacEmergencyLeadRouting } from '@/domains/case-studies/content/HvacEmergencyLeadRouting';
import { hvacMaintenancePlanReactivation } from '@/domains/case-studies/content/HvacMaintenancePlanReactivation';
import { hvacSeasonalLeadSurgeHandling } from '@/domains/case-studies/content/HvacSeasonalLeadSurgeHandling';
import { lawFirmClientIntakeAutomation } from '@/domains/case-studies/content/LawFirmClientIntakeAutomation';
import { lawFirmConsultationBookingSystem } from '@/domains/case-studies/content/LawFirmConsultationBookingSystem';
import { localAuthoritySystemImpact } from '@/domains/case-studies/content/LocalAuthoritySystemImpact';
import { realEstateInquiryRouting } from '@/domains/case-studies/content/RealEstateInquiryRouting';
import { realtorLeadFollowUpAutomation } from '@/domains/case-studies/content/RealtorLeadFollowUpAutomation';
import { roofingEstimateFollowUpAutomation } from '@/domains/case-studies/content/RoofingEstimateFollowUpAutomation';
import { roofingWebsiteRebuildWithCrm } from '@/domains/case-studies/content/RoofingWebsiteRebuildWithCrm';
import { salonBookingAutomation } from '@/domains/case-studies/content/SalonBookingAutomation';
import { salonNoShowReductionSystem } from '@/domains/case-studies/content/SalonNoShowReductionSystem';
import { salonReviewGenerationAutomation } from '@/domains/case-studies/content/SalonReviewGenerationAutomation';
import { smartWebsiteInfrastructureImplementation } from '@/domains/case-studies/content/SmartWebsiteInfrastructureImplementation';
import { stormSeasonLeadHandlingSystem } from '@/domains/case-studies/content/StormSeasonLeadHandlingSystem';
import type { CaseStudyData } from '@/domains/case-studies/types';

export const CASE_STUDY_REGISTRY: Record<string, CaseStudyData> = {
  'appointment-business-booking-automation': appointmentBusinessBookingAutomation,
  'appointment-reminder-no-show-reduction': appointmentReminderNoShowReduction,
  'auto-repair-missed-call-recovery': autoRepairMissedCallRecovery,
  'automotive-service-reminder-automation': automotiveServiceReminderAutomation,
  'beauty-salon-online-booking-local-seo-manchester-all-sections': beautySalonManchesterAllSections,
  'beauty-salon-online-booking-local-seo-manchester-custom': beautySalonManchesterCustom,
  'crm-pipeline-visibility-transformation': crmPipelineVisibilityTransformation,
  'hvac-emergency-lead-routing': hvacEmergencyLeadRouting,
  'hvac-maintenance-plan-reactivation': hvacMaintenancePlanReactivation,
  'hvac-seasonal-lead-surge-handling': hvacSeasonalLeadSurgeHandling,
  'law-firm-client-intake-automation': lawFirmClientIntakeAutomation,
  'law-firm-consultation-booking-system': lawFirmConsultationBookingSystem,
  'local-authority-system-impact': localAuthoritySystemImpact,
  'real-estate-inquiry-routing': realEstateInquiryRouting,
  'realtor-lead-follow-up-automation': realtorLeadFollowUpAutomation,
  'roofing-estimate-follow-up-automation': roofingEstimateFollowUpAutomation,
  'roofing-website-rebuild-with-crm': roofingWebsiteRebuildWithCrm,
  'salon-booking-automation': salonBookingAutomation,
  'salon-no-show-reduction-system': salonNoShowReductionSystem,
  'salon-review-generation-automation': salonReviewGenerationAutomation,
  'smart-website-infrastructure-implementation': smartWebsiteInfrastructureImplementation,
  'storm-season-lead-handling-system': stormSeasonLeadHandlingSystem,
};

export const caseStudies = Object.values(CASE_STUDY_REGISTRY);
