// AUTO-GENERATED by scripts/generate-content-registries.mjs. Do not edit manually.
import { appointmentBusinessBookingAutomation } from '@/domains/case-studies/content/AppointmentBusinessBookingAutomation';
import { appointmentReminderNoShowReduction } from '@/domains/case-studies/content/AppointmentReminderNoShowReduction';
import { automotiveServiceReminderAutomation } from '@/domains/case-studies/content/AutomotiveServiceReminderAutomation';
import { beautySalonManchesterAllSections } from '@/domains/case-studies/content/BeautySalonManchesterAllSections';
import { beautySalonManchesterCustom } from '@/domains/case-studies/content/BeautySalonManchesterCustom';
import { crmPipelineVisibilityTransformation } from '@/domains/case-studies/content/CrmPipelineVisibilityTransformation';
import { localAuthoritySystemImpact } from '@/domains/case-studies/content/LocalAuthoritySystemImpact';
import { autoRepairMissedCallRecovery } from '@/domains/case-studies/content/AutoRepairMissedCallRecovery';
import { hvacEmergencyLeadRouting } from '@/domains/case-studies/content/HvacEmergencyLeadRouting';
import { hvacMaintenancePlanReactivation } from '@/domains/case-studies/content/HvacMaintenancePlanReactivation';
import { hvacSeasonalLeadSurgeHandling } from '@/domains/case-studies/content/HvacSeasonalLeadSurgeHandling';
import { lawFirmConsultationBookingSystem } from '@/domains/case-studies/content/LawFirmConsultationBookingSystem';
import { lawFirmClientIntakeAutomation } from '@/domains/case-studies/content/LawFirmClientIntakeAutomation';
import { smartWebsiteInfrastructureImplementation } from '@/domains/case-studies/content/SmartWebsiteInfrastructureImplementation';
import { realEstateInquiryRouting } from '@/domains/case-studies/content/RealEstateInquiryRouting';
import { realtorLeadFollowUpAutomation } from '@/domains/case-studies/content/RealtorLeadFollowUpAutomation';
import { roofingEstimateFollowUpAutomation } from '@/domains/case-studies/content/RoofingEstimateFollowUpAutomation';
import { stormSeasonLeadHandlingSystem } from '@/domains/case-studies/content/StormSeasonLeadHandlingSystem';
import { roofingWebsiteRebuildWithCrm } from '@/domains/case-studies/content/RoofingWebsiteRebuildWithCrm';
import { salonBookingAutomation } from '@/domains/case-studies/content/SalonBookingAutomation';
import { salonNoShowReductionSystem } from '@/domains/case-studies/content/SalonNoShowReductionSystem';
import { salonReviewGenerationAutomation } from '@/domains/case-studies/content/SalonReviewGenerationAutomation';
import type { CaseStudyData } from '@/domains/case-studies/types';

export const CASE_STUDY_REGISTRY: Record<string, CaseStudyData> = {
  'appointment-business-booking-automation': appointmentBusinessBookingAutomation,
  'appointment-reminder-no-show-reduction': appointmentReminderNoShowReduction,
  'automotive-service-reminder-automation': automotiveServiceReminderAutomation,
  'beauty-salon-online-booking-local-seo-manchester-all-sections': beautySalonManchesterAllSections,
  'beauty-salon-online-booking-local-seo-manchester-custom': beautySalonManchesterCustom,
  'crm-pipeline-visibility-transformation': crmPipelineVisibilityTransformation,
  'electrician-not-showing-up-where-locals-search': localAuthoritySystemImpact,
  'garage-morning-rush-missed-calls': autoRepairMissedCallRecovery,
  'hvac-after-hours-calls-going-cold': hvacEmergencyLeadRouting,
  'hvac-maintenance-plan-reactivation': hvacMaintenancePlanReactivation,
  'hvac-seasonal-lead-surge-handling': hvacSeasonalLeadSurgeHandling,
  'law-firm-consultation-booking-system': lawFirmConsultationBookingSystem,
  'law-firm-intake-stalled-after-first-enquiry': lawFirmClientIntakeAutomation,
  'plumbing-website-looked-fine-but-underperformed': smartWebsiteInfrastructureImplementation,
  'real-estate-inquiry-routing': realEstateInquiryRouting,
  'realtor-lead-follow-up-automation': realtorLeadFollowUpAutomation,
  'roofing-quotes-not-being-followed-up': roofingEstimateFollowUpAutomation,
  'roofing-storm-calls-overwhelmed-the-team': stormSeasonLeadHandlingSystem,
  'roofing-website-rebuild-with-crm': roofingWebsiteRebuildWithCrm,
  'salon-booking-automation': salonBookingAutomation,
  'salon-no-show-reduction-system': salonNoShowReductionSystem,
  'salon-review-generation-automation': salonReviewGenerationAutomation,
};

export const caseStudies = Object.values(CASE_STUDY_REGISTRY);
