/**
 * Content Mapping System (Phase 10.1)
 *
 * Centralized control layer for content intent, primary system, and CTA targets.
 * Used by ctaResolver to drive deterministic CTA routing without editing content files.
 *
 * Generated from reports/phase10-content-audit.json
 * Validated by scripts/analyzers/validate-content-mapping.ts
 *
 * AUTO-GENERATED — Do not edit manually without re-running validator.
 * Generated: 2026-04-05T22:06:36.897Z
 * Total: 127 mappings (75 blogs, 52 resources)
 */

import type { BlogIntent, ResourceIntent } from '@/lib/ui/ctaEngine';

export type ContentMapping = {
  slug: string;
  contentType: 'blog' | 'resource';
  intent: BlogIntent | ResourceIntent;
  primarySystem?: string;
  ctaTarget?: string;
  notes?: string;
};

/** Lookup helper: returns mapping for a given contentType + slug */
export function getContentMapping(contentType: 'blog' | 'resource', slug: string): ContentMapping | undefined {
  return CONTENT_MAPPING[contentType + ':' + slug];
}

export const CONTENT_MAPPING: Record<string, ContentMapping> = {
  'blog:ai-reception-for-automotive-shops': {
    slug: 'ai-reception-for-automotive-shops',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:authority-signals-for-local-search': {
    slug: 'authority-signals-for-local-search',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'blog:authority-signals-for-salons': {
    slug: 'authority-signals-for-salons',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
    notes: 'multi-system: [local-seo-authority, reputation-review] → using \'local-seo-authority\'' ,
  },
  'blog:automotive-crm-pipeline-for-repair-jobs': {
    slug: 'automotive-crm-pipeline-for-repair-jobs',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:automotive-review-generation-system': {
    slug: 'automotive-review-generation-system',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'blog:automotive-service-reminders-explained': {
    slug: 'automotive-service-reminders-explained',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'blog:autonomous-booking-systems-for-salons': {
    slug: 'autonomous-booking-systems-for-salons',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
    notes: 'low-confidence: fallback rule (default-fallback); multi-system: [smart-website-systems, crm-automation] → using \'smart-website-systems\'' ,
  },
  'blog:booking-systems-for-salons-explained': {
    slug: 'booking-systems-for-salons-explained',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
    notes: 'multi-system: [smart-website-systems, crm-automation] → using \'smart-website-systems\'' ,
  },
  'blog:building-revenue-visibility-through-crm-tracking': {
    slug: 'building-revenue-visibility-through-crm-tracking',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'blog:client-reactivation-for-salons': {
    slug: 'client-reactivation-for-salons',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:client-reactivation-systems-for-service-businesses': {
    slug: 'client-reactivation-systems-for-service-businesses',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:conversion-tracking-for-hvac-companies': {
    slug: 'conversion-tracking-for-hvac-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
    notes: 'multi-system: [smart-website-systems, crm-automation] → using \'smart-website-systems\'' ,
  },
  'blog:conversion-tracking-for-service-businesses-explained': {
    slug: 'conversion-tracking-for-service-businesses-explained',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'blog:crm-pipeline-architecture-for-service-businesses': {
    slug: 'crm-pipeline-architecture-for-service-businesses',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'blog:customer-feedback-loop-for-plumbing-companies': {
    slug: 'customer-feedback-loop-for-plumbing-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:customer-feedback-loop-framework-for-service-businesses': {
    slug: 'customer-feedback-loop-framework-for-service-businesses',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'blog:future-crm-visibility-for-hvac-companies': {
    slug: 'future-crm-visibility-for-hvac-companies',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'blog:future-local-seo-after-google-business-profile-automation': {
    slug: 'future-local-seo-after-google-business-profile-automation',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'blog:google-business-profile-for-hvac-companies': {
    slug: 'google-business-profile-for-hvac-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:google-business-profile-system-architecture': {
    slug: 'google-business-profile-system-architecture',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'blog:how-ai-search-changes-local-business-visibility': {
    slug: 'how-ai-search-changes-local-business-visibility',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'blog:how-review-automation-improves-local-authority': {
    slug: 'how-review-automation-improves-local-authority',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'blog:how-smart-website-systems-work-for-local-businesses': {
    slug: 'how-smart-website-systems-work-for-local-businesses',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'blog:hvac-crm-pipeline-for-service-companies': {
    slug: 'hvac-crm-pipeline-for-service-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:hvac-emergency-call-handling-mistakes': {
    slug: 'hvac-emergency-call-handling-mistakes',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
    notes: 'multi-system: [ai-lead-handling, crm-automation] → using \'ai-lead-handling\'' ,
  },
  'blog:hvac-review-generation-framework': {
    slug: 'hvac-review-generation-framework',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'blog:lead-automation-framework-for-service-businesses': {
    slug: 'lead-automation-framework-for-service-businesses',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:lead-qualification-for-roofing-companies': {
    slug: 'lead-qualification-for-roofing-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:lead-qualification-framework-for-service-businesses': {
    slug: 'lead-qualification-framework-for-service-businesses',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:lead-response-time-for-service-businesses': {
    slug: 'lead-response-time-for-service-businesses',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:lead-routing-for-hvac-companies': {
    slug: 'lead-routing-for-hvac-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:lead-routing-models-for-service-companies': {
    slug: 'lead-routing-models-for-service-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:local-seo-for-roofing-companies-explained': {
    slug: 'local-seo-for-roofing-companies-explained',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'blog:local-seo-vs-website-optimization': {
    slug: 'local-seo-vs-website-optimization',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'blog:local-service-page-architecture-for-local-businesses': {
    slug: 'local-service-page-architecture-for-local-businesses',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'blog:local-service-page-architecture-for-roofing-companies': {
    slug: 'local-service-page-architecture-for-roofing-companies',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
    notes: 'multi-system: [local-seo-authority, smart-website-systems] → using \'local-seo-authority\'' ,
  },
  'blog:local-visibility-framework-for-service-businesses': {
    slug: 'local-visibility-framework-for-service-businesses',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'blog:missed-call-recovery-for-service-businesses': {
    slug: 'missed-call-recovery-for-service-businesses',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:multi-channel-lead-capture-for-salons': {
    slug: 'multi-channel-lead-capture-for-salons',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:multi-channel-lead-capture-system-for-service-businesses': {
    slug: 'multi-channel-lead-capture-system-for-service-businesses',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:negative-reviews-for-auto-repair-shops': {
    slug: 'negative-reviews-for-auto-repair-shops',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:reducing-salon-no-shows-with-automation': {
    slug: 'reducing-salon-no-shows-with-automation',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
    notes: 'multi-system: [crm-automation, ai-lead-handling] → using \'crm-automation\'' ,
  },
  'blog:reputation-monitoring-systems-for-service-businesses': {
    slug: 'reputation-monitoring-systems-for-service-businesses',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:responding-to-negative-reviews-systematically': {
    slug: 'responding-to-negative-reviews-systematically',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:revenue-visibility-for-roofing-companies': {
    slug: 'revenue-visibility-for-roofing-companies',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'blog:review-automation-for-hvac-companies': {
    slug: 'review-automation-for-hvac-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'blog:review-automation-for-roofing-companies': {
    slug: 'review-automation-for-roofing-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'blog:review-automation-for-salons': {
    slug: 'review-automation-for-salons',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'blog:review-generation-system-for-local-businesses': {
    slug: 'review-generation-system-for-local-businesses',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'blog:roofing-crm-pipeline-for-estimates': {
    slug: 'roofing-crm-pipeline-for-estimates',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:roofing-estimate-follow-up-delays': {
    slug: 'roofing-estimate-follow-up-delays',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
    notes: 'multi-system: [ai-lead-handling, crm-automation] → using \'ai-lead-handling\'' ,
  },
  'blog:roofing-review-generation-system': {
    slug: 'roofing-review-generation-system',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'blog:sales-pipeline-visibility-for-hvac-companies': {
    slug: 'sales-pipeline-visibility-for-hvac-companies',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'blog:sales-pipeline-visibility-framework': {
    slug: 'sales-pipeline-visibility-framework',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'blog:salon-review-generation-framework': {
    slug: 'salon-review-generation-framework',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'blog:service-business-follow-up-automation': {
    slug: 'service-business-follow-up-automation',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:service-page-architecture-for-service-businesses': {
    slug: 'service-page-architecture-for-service-businesses',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'blog:smart-website-systems-for-roofing-companies': {
    slug: 'smart-website-systems-for-roofing-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:systems-first-website-for-hvac-companies': {
    slug: 'systems-first-website-for-hvac-companies',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:tracking-customer-lifetime-value-using-crm': {
    slug: 'tracking-customer-lifetime-value-using-crm',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'blog:tracking-salon-client-lifetime-value': {
    slug: 'tracking-salon-client-lifetime-value',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'blog:website-crm-integration-for-salons': {
    slug: 'website-crm-integration-for-salons',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:website-crm-integration-for-service-businesses': {
    slug: 'website-crm-integration-for-service-businesses',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:website-design-that-supports-crm-systems': {
    slug: 'website-design-that-supports-crm-systems',
    contentType: 'blog',
    intent: 'SYSTEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'blog:what-is-a-systems-first-website-for-service-businesses': {
    slug: 'what-is-a-systems-first-website-for-service-businesses',
    contentType: 'blog',
    intent: 'FRAMEWORK',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'blog:why-auto-repair-missed-calls-lose-booked-work': {
    slug: 'why-auto-repair-missed-calls-lose-booked-work',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:why-auto-repair-shops-lose-phone-leads': {
    slug: 'why-auto-repair-shops-lose-phone-leads',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:why-booking-systems-need-website-infrastructure': {
    slug: 'why-booking-systems-need-website-infrastructure',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'blog:why-hvac-companies-lose-leads-after-hours': {
    slug: 'why-hvac-companies-lose-leads-after-hours',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:why-hvac-missed-calls-lose-after-hours-revenue': {
    slug: 'why-hvac-missed-calls-lose-after-hours-revenue',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:why-roofing-companies-lose-leads-during-storm-season': {
    slug: 'why-roofing-companies-lose-leads-during-storm-season',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:why-roofing-missed-calls-cost-emergency-jobs': {
    slug: 'why-roofing-missed-calls-cost-emergency-jobs',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:why-salons-lose-calls-during-service-hours': {
    slug: 'why-salons-lose-calls-during-service-hours',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:why-salons-need-lead-handling-systems': {
    slug: 'why-salons-need-lead-handling-systems',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'blog:why-service-business-websites-fail-to-convert': {
    slug: 'why-service-business-websites-fail-to-convert',
    contentType: 'blog',
    intent: 'PROBLEM',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'resource:authority-signals-for-local-search': {
    slug: 'authority-signals-for-local-search',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'resource:auto-repair-lead-handling-example': {
    slug: 'auto-repair-lead-handling-example',
    contentType: 'resource',
    intent: 'EXAMPLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
    notes: 'multi-system: [ai-lead-handling, smart-website-systems] → using \'ai-lead-handling\'' ,
  },
  'resource:auto-reply-funnel': {
    slug: 'auto-reply-funnel',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:automotive-crm-pipeline-for-repair-jobs': {
    slug: 'automotive-crm-pipeline-for-repair-jobs',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'resource:automotive-review-generation-system': {
    slug: 'automotive-review-generation-system',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'resource:automotive-service-reminder-automation': {
    slug: 'automotive-service-reminder-automation',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'resource:booking-systems-inside-website-infrastructure': {
    slug: 'booking-systems-inside-website-infrastructure',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'resource:building-revenue-visibility-through-crm-tracking': {
    slug: 'building-revenue-visibility-through-crm-tracking',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'resource:client-reactivation-systems': {
    slug: 'client-reactivation-systems',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'resource:conversion-architecture-for-service-websites': {
    slug: 'conversion-architecture-for-service-websites',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'resource:conversion-tracking-for-service-businesses': {
    slug: 'conversion-tracking-for-service-businesses',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'resource:crm-pipeline-architecture': {
    slug: 'crm-pipeline-architecture',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'resource:crm-pipeline-automation': {
    slug: 'crm-pipeline-automation',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'revenue-growth',
    ctaTarget: '/services/growth-revenue-systems',
  },
  'resource:customer-feedback-loop-framework': {
    slug: 'customer-feedback-loop-framework',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'resource:designing-websites-that-support-crm-systems': {
    slug: 'designing-websites-that-support-crm-systems',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'resource:google-business-profile-system-architecture': {
    slug: 'google-business-profile-system-architecture',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'resource:how-review-automation-improves-local-authority': {
    slug: 'how-review-automation-improves-local-authority',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'resource:how-smart-website-systems-work': {
    slug: 'how-smart-website-systems-work',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'resource:hvac-crm-pipeline-structure': {
    slug: 'hvac-crm-pipeline-structure',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'resource:hvac-emergency-call-handling-system': {
    slug: 'hvac-emergency-call-handling-system',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
    notes: 'multi-system: [ai-lead-handling, crm-automation] → using \'ai-lead-handling\'' ,
  },
  'resource:hvac-lead-handling-example': {
    slug: 'hvac-lead-handling-example',
    contentType: 'resource',
    intent: 'EXAMPLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:hvac-review-generation-framework': {
    slug: 'hvac-review-generation-framework',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'resource:lead-automation-framework': {
    slug: 'lead-automation-framework',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:lead-qualification-framework': {
    slug: 'lead-qualification-framework',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:lead-response-time-framework': {
    slug: 'lead-response-time-framework',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:lead-routing-models-for-service-companies': {
    slug: 'lead-routing-models-for-service-companies',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:local-seo-vs-website-optimization': {
    slug: 'local-seo-vs-website-optimization',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'resource:local-service-page-architecture': {
    slug: 'local-service-page-architecture',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
    notes: 'multi-system: [local-seo-authority, smart-website-systems] → using \'local-seo-authority\'' ,
  },
  'resource:local-visibility-framework': {
    slug: 'local-visibility-framework',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'local-seo-authority',
    ctaTarget: '/services/local-seo-authority',
  },
  'resource:missed-call-recovery-for-auto-repair': {
    slug: 'missed-call-recovery-for-auto-repair',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:missed-call-recovery-for-hvac': {
    slug: 'missed-call-recovery-for-hvac',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:missed-call-recovery-for-roofing': {
    slug: 'missed-call-recovery-for-roofing',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:missed-call-recovery-for-salons': {
    slug: 'missed-call-recovery-for-salons',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:missed-call-recovery-system': {
    slug: 'missed-call-recovery-system',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:multi-channel-lead-capture-systems': {
    slug: 'multi-channel-lead-capture-systems',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:reducing-salon-no-shows-with-automation': {
    slug: 'reducing-salon-no-shows-with-automation',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
    notes: 'low-confidence: fallback rule (default-fallback); multi-system: [crm-automation, ai-lead-handling] → using \'crm-automation\'' ,
  },
  'resource:reputation-monitoring-systems': {
    slug: 'reputation-monitoring-systems',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'resource:responding-to-negative-reviews-systematically': {
    slug: 'responding-to-negative-reviews-systematically',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
    notes: 'low-confidence: fallback rule (default-fallback)' ,
  },
  'resource:review-generation-system': {
    slug: 'review-generation-system',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'resource:roofing-crm-pipeline-structure': {
    slug: 'roofing-crm-pipeline-structure',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'resource:roofing-estimate-follow-up-workflow': {
    slug: 'roofing-estimate-follow-up-workflow',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
    notes: 'multi-system: [ai-lead-handling, crm-automation] → using \'ai-lead-handling\'' ,
  },
  'resource:roofing-lead-handling-example': {
    slug: 'roofing-lead-handling-example',
    contentType: 'resource',
    intent: 'EXAMPLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:roofing-review-generation-system': {
    slug: 'roofing-review-generation-system',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'resource:sales-pipeline-visibility-framework': {
    slug: 'sales-pipeline-visibility-framework',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'resource:salon-lead-handling-example': {
    slug: 'salon-lead-handling-example',
    contentType: 'resource',
    intent: 'EXAMPLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:salon-review-generation-framework': {
    slug: 'salon-review-generation-framework',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'reputation-review',
    ctaTarget: '/services/reputation-review-systems',
  },
  'resource:service-business-follow-up-automation-guide': {
    slug: 'service-business-follow-up-automation-guide',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'ai-lead-handling',
    ctaTarget: '/services/ai-lead-handling',
  },
  'resource:service-page-architecture-that-converts': {
    slug: 'service-page-architecture-that-converts',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'resource:tracking-customer-lifetime-value-using-crm': {
    slug: 'tracking-customer-lifetime-value-using-crm',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
  },
  'resource:tracking-salon-client-lifetime-value': {
    slug: 'tracking-salon-client-lifetime-value',
    contentType: 'resource',
    intent: 'ACTIONABLE',
    primarySystem: 'crm-automation',
    ctaTarget: '/services/crm-infrastructure-implementation',
    notes: 'multi-system: [crm-automation, revenue-growth] → using \'crm-automation\'' ,
  },
  'resource:website-crm-integration-explained': {
    slug: 'website-crm-integration-explained',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
  'resource:what-is-a-systems-first-website': {
    slug: 'what-is-a-systems-first-website',
    contentType: 'resource',
    intent: 'EDUCATIONAL',
    primarySystem: 'smart-website-systems',
    ctaTarget: '/services/smart-website-systems',
  },
};
