// AUTO-GENERATED by scripts/generate-content-registries.mjs. Do not edit manually.
import { aiReceptionForAutomotiveShops } from '@/domains/blog/content/AiReceptionForAutomotiveShops';
import { authoritySignalsForLocalSearch } from '@/domains/blog/content/AuthoritySignalsForLocalSearch';
import { authoritySignalsForSalons } from '@/domains/blog/content/AuthoritySignalsForSalons';
import { automotiveCrmPipelineForRepairJobs } from '@/domains/blog/content/AutomotiveCrmPipelineForRepairJobs';
import { automotiveReviewGenerationSystem } from '@/domains/blog/content/AutomotiveReviewGenerationSystem';
import { automotiveServiceRemindersExplained } from '@/domains/blog/content/AutomotiveServiceRemindersExplained';
import { autonomousBookingSystemsForSalons } from '@/domains/blog/content/AutonomousBookingSystemsForSalons';
import { bookingSystemsForSalonsExplained } from '@/domains/blog/content/BookingSystemsForSalonsExplained';
import { buildingRevenueVisibilityThroughCrmTracking } from '@/domains/blog/content/BuildingRevenueVisibilityThroughCrmTracking';
import { clientReactivationForSalons } from '@/domains/blog/content/ClientReactivationForSalons';
import { clientReactivationSystemsForServiceBusinesses } from '@/domains/blog/content/ClientReactivationSystemsForServiceBusinesses';
import { conversionTrackingForHvacCompanies } from '@/domains/blog/content/ConversionTrackingForHvacCompanies';
import { conversionTrackingForServiceBusinessesExplained } from '@/domains/blog/content/ConversionTrackingForServiceBusinessesExplained';
import { crmPipelineArchitectureForServiceBusinesses } from '@/domains/blog/content/CrmPipelineArchitectureForServiceBusinesses';
import { customerFeedbackLoopForPlumbingCompanies } from '@/domains/blog/content/CustomerFeedbackLoopForPlumbingCompanies';
import { customerFeedbackLoopFrameworkForServiceBusinesses } from '@/domains/blog/content/CustomerFeedbackLoopFrameworkForServiceBusinesses';
import { futureCrmVisibilityForHvacCompanies } from '@/domains/blog/content/FutureCrmVisibilityForHvacCompanies';
import { futureLocalSeoAfterGoogleBusinessProfileAutomation } from '@/domains/blog/content/FutureLocalSeoAfterGoogleBusinessProfileAutomation';
import { googleBusinessProfileForHvacCompanies } from '@/domains/blog/content/GoogleBusinessProfileForHvacCompanies';
import { googleBusinessProfileSystemArchitecture } from '@/domains/blog/content/GoogleBusinessProfileSystemArchitecture';
import { howAiSearchChangesLocalBusinessVisibility } from '@/domains/blog/content/HowAiSearchChangesLocalBusinessVisibility';
import { howReviewAutomationImprovesLocalAuthority } from '@/domains/blog/content/HowReviewAutomationImprovesLocalAuthority';
import { howSmartWebsiteSystemsWorkForLocalBusinesses } from '@/domains/blog/content/HowSmartWebsiteSystemsWorkForLocalBusinesses';
import { howToFixLeadResponseTimeInAutomotiveBusinessesUsingCrmAutomation } from '@/domains/blog/content/HowToFixLeadResponseTimeInAutomotiveBusinessesUsingCrmAutomation';
import { hvacCrmPipelineForServiceCompanies } from '@/domains/blog/content/HvacCrmPipelineForServiceCompanies';
import { hvacEmergencyCallHandlingMistakes } from '@/domains/blog/content/HvacEmergencyCallHandlingMistakes';
import { hvacLocalVisibilitySystemForServiceAreas } from '@/domains/blog/content/HvacLocalVisibilitySystemForServiceAreas';
import { hvacReviewGenerationFramework } from '@/domains/blog/content/HvacReviewGenerationFramework';
import { leadAutomationFrameworkForServiceBusinesses } from '@/domains/blog/content/LeadAutomationFrameworkForServiceBusinesses';
import { leadQualificationForRoofingCompanies } from '@/domains/blog/content/LeadQualificationForRoofingCompanies';
import { leadQualificationFrameworkForServiceBusinesses } from '@/domains/blog/content/LeadQualificationFrameworkForServiceBusinesses';
import { leadResponseTimeForServiceBusinesses } from '@/domains/blog/content/LeadResponseTimeForServiceBusinesses';
import { leadRoutingForHvacCompanies } from '@/domains/blog/content/LeadRoutingForHvacCompanies';
import { leadRoutingModelsForServiceCompanies } from '@/domains/blog/content/LeadRoutingModelsForServiceCompanies';
import { localSeoForRoofingCompaniesExplained } from '@/domains/blog/content/LocalSeoForRoofingCompaniesExplained';
import { localSeoVsWebsiteOptimization } from '@/domains/blog/content/LocalSeoVsWebsiteOptimization';
import { localServicePageArchitectureForLocalBusinesses } from '@/domains/blog/content/LocalServicePageArchitectureForLocalBusinesses';
import { localServicePageArchitectureForRoofingCompanies } from '@/domains/blog/content/LocalServicePageArchitectureForRoofingCompanies';
import { localVisibilityFrameworkForServiceBusinesses } from '@/domains/blog/content/LocalVisibilityFrameworkForServiceBusinesses';
import { missedCallRecoveryForServiceBusinesses } from '@/domains/blog/content/MissedCallRecoveryForServiceBusinesses';
import { multiChannelLeadCaptureForSalons } from '@/domains/blog/content/MultiChannelLeadCaptureForSalons';
import { multiChannelLeadCaptureSystemForServiceBusinesses } from '@/domains/blog/content/MultiChannelLeadCaptureSystemForServiceBusinesses';
import { negativeReviewsForAutoRepairShops } from '@/domains/blog/content/NegativeReviewsForAutoRepairShops';
import { plumbingCrmPipelineForJobManagement } from '@/domains/blog/content/PlumbingCrmPipelineForJobManagement';
import { realtorLocalVisibilitySystemForLeadGeneration } from '@/domains/blog/content/RealtorLocalVisibilitySystemForLeadGeneration';
import { reducingSalonNoShowsWithAutomation } from '@/domains/blog/content/ReducingSalonNoShowsWithAutomation';
import { reputationMonitoringSystemsForServiceBusinesses } from '@/domains/blog/content/ReputationMonitoringSystemsForServiceBusinesses';
import { respondingToNegativeReviewsSystematically } from '@/domains/blog/content/RespondingToNegativeReviewsSystematically';
import { revenueVisibilityForRoofingCompanies } from '@/domains/blog/content/RevenueVisibilityForRoofingCompanies';
import { reviewAutomationForHvacCompanies } from '@/domains/blog/content/ReviewAutomationForHvacCompanies';
import { reviewAutomationForRoofingCompanies } from '@/domains/blog/content/ReviewAutomationForRoofingCompanies';
import { reviewAutomationForSalons } from '@/domains/blog/content/ReviewAutomationForSalons';
import { reviewGenerationSystemForLocalBusinesses } from '@/domains/blog/content/ReviewGenerationSystemForLocalBusinesses';
import { roofingCrmPipelineForEstimates } from '@/domains/blog/content/RoofingCrmPipelineForEstimates';
import { roofingEstimateFollowUpDelays } from '@/domains/blog/content/RoofingEstimateFollowUpDelays';
import { roofingReviewGenerationSystem } from '@/domains/blog/content/RoofingReviewGenerationSystem';
import { salesPipelineVisibilityForHvacCompanies } from '@/domains/blog/content/SalesPipelineVisibilityForHvacCompanies';
import { salesPipelineVisibilityFramework } from '@/domains/blog/content/SalesPipelineVisibilityFramework';
import { salonCrmPipelineForClientRetention } from '@/domains/blog/content/SalonCrmPipelineForClientRetention';
import { salonReviewGenerationFramework } from '@/domains/blog/content/SalonReviewGenerationFramework';
import { serviceBusinessFollowUpAutomation } from '@/domains/blog/content/ServiceBusinessFollowUpAutomation';
import { servicePageArchitectureForServiceBusinesses } from '@/domains/blog/content/ServicePageArchitectureForServiceBusinesses';
import { smartWebsiteSystemsForRoofingCompanies } from '@/domains/blog/content/SmartWebsiteSystemsForRoofingCompanies';
import { systemsFirstWebsiteForHvacCompanies } from '@/domains/blog/content/SystemsFirstWebsiteForHvacCompanies';
import { trackingCustomerLifetimeValueUsingCrm } from '@/domains/blog/content/TrackingCustomerLifetimeValueUsingCrm';
import { trackingSalonClientLifetimeValue } from '@/domains/blog/content/TrackingSalonClientLifetimeValue';
import { websiteCrmIntegrationForSalons } from '@/domains/blog/content/WebsiteCrmIntegrationForSalons';
import { websiteCrmIntegrationForServiceBusinesses } from '@/domains/blog/content/WebsiteCrmIntegrationForServiceBusinesses';
import { websiteDesignThatSupportsCrmSystems } from '@/domains/blog/content/WebsiteDesignThatSupportsCrmSystems';
import { whatIsASystemsFirstWebsiteForServiceBusinesses } from '@/domains/blog/content/WhatIsASystemsFirstWebsiteForServiceBusinesses';
import { whyAutoRepairMissedCallsLoseBookedWork } from '@/domains/blog/content/WhyAutoRepairMissedCallsLoseBookedWork';
import { whyAutoRepairShopsLosePhoneLeads } from '@/domains/blog/content/WhyAutoRepairShopsLosePhoneLeads';
import { whyBookingSystemsNeedWebsiteInfrastructure } from '@/domains/blog/content/WhyBookingSystemsNeedWebsiteInfrastructure';
import { whyHvacCompaniesDisappearFromLocalSearch } from '@/domains/blog/content/WhyHvacCompaniesDisappearFromLocalSearch';
import { whyHvacCompaniesLoseLeadsAfterHours } from '@/domains/blog/content/WhyHvacCompaniesLoseLeadsAfterHours';
import { whyHvacMissedCallsLoseAfterHoursRevenue } from '@/domains/blog/content/WhyHvacMissedCallsLoseAfterHoursRevenue';
import { whyPlumbingCompaniesLoseJobsWithoutCrmPipeline } from '@/domains/blog/content/WhyPlumbingCompaniesLoseJobsWithoutCrmPipeline';
import { whyRealtorsLoseLeadsWithoutLocalVisibility } from '@/domains/blog/content/WhyRealtorsLoseLeadsWithoutLocalVisibility';
import { whyRoofingCompaniesLoseJobsWithoutReviewAutomation } from '@/domains/blog/content/WhyRoofingCompaniesLoseJobsWithoutReviewAutomation';
import { whyRoofingCompaniesLoseLeadsDuringStormSeason } from '@/domains/blog/content/WhyRoofingCompaniesLoseLeadsDuringStormSeason';
import { whyRoofingMissedCallsCostEmergencyJobs } from '@/domains/blog/content/WhyRoofingMissedCallsCostEmergencyJobs';
import { whySalonsLoseCallsDuringServiceHours } from '@/domains/blog/content/WhySalonsLoseCallsDuringServiceHours';
import { whySalonsLoseClientsWithoutCrmPipeline } from '@/domains/blog/content/WhySalonsLoseClientsWithoutCrmPipeline';
import { whySalonsLoseClientsWithoutReviewAutomation } from '@/domains/blog/content/WhySalonsLoseClientsWithoutReviewAutomation';
import { whySalonsNeedLeadHandlingSystems } from '@/domains/blog/content/WhySalonsNeedLeadHandlingSystems';
import { whyServiceBusinessWebsitesFailToConvert } from '@/domains/blog/content/WhyServiceBusinessWebsitesFailToConvert';
import { whySlowLeadResponseIsKillingAutomotiveBusinesses } from '@/domains/blog/content/WhySlowLeadResponseIsKillingAutomotiveBusinesses';
import { whySlowLeadResponseIsKillingHvacBusinesses } from '@/domains/blog/content/WhySlowLeadResponseIsKillingHvacBusinesses';
import type { BlogPostData } from '@/domains/blog/types';

export const BLOG_POSTS: Record<string, BlogPostData> = {
  'ai-reception-for-automotive-shops': aiReceptionForAutomotiveShops,
  'authority-signals-for-local-search': authoritySignalsForLocalSearch,
  'authority-signals-for-salons': authoritySignalsForSalons,
  'automotive-crm-pipeline-for-repair-jobs': automotiveCrmPipelineForRepairJobs,
  'automotive-review-generation-system': automotiveReviewGenerationSystem,
  'automotive-service-reminders-explained': automotiveServiceRemindersExplained,
  'autonomous-booking-systems-for-salons': autonomousBookingSystemsForSalons,
  'booking-systems-for-salons-explained': bookingSystemsForSalonsExplained,
  'building-revenue-visibility-through-crm-tracking': buildingRevenueVisibilityThroughCrmTracking,
  'client-reactivation-for-salons': clientReactivationForSalons,
  'client-reactivation-systems-for-service-businesses': clientReactivationSystemsForServiceBusinesses,
  'conversion-tracking-for-hvac-companies': conversionTrackingForHvacCompanies,
  'conversion-tracking-for-service-businesses-explained': conversionTrackingForServiceBusinessesExplained,
  'crm-pipeline-architecture-for-service-businesses': crmPipelineArchitectureForServiceBusinesses,
  'customer-feedback-loop-for-plumbing-companies': customerFeedbackLoopForPlumbingCompanies,
  'customer-feedback-loop-framework-for-service-businesses': customerFeedbackLoopFrameworkForServiceBusinesses,
  'future-crm-visibility-for-hvac-companies': futureCrmVisibilityForHvacCompanies,
  'future-local-seo-after-google-business-profile-automation': futureLocalSeoAfterGoogleBusinessProfileAutomation,
  'google-business-profile-for-hvac-companies': googleBusinessProfileForHvacCompanies,
  'google-business-profile-system-architecture': googleBusinessProfileSystemArchitecture,
  'how-ai-search-changes-local-business-visibility': howAiSearchChangesLocalBusinessVisibility,
  'how-review-automation-improves-local-authority': howReviewAutomationImprovesLocalAuthority,
  'how-smart-website-systems-work-for-local-businesses': howSmartWebsiteSystemsWorkForLocalBusinesses,
  'how-to-fix-lead-response-time-in-automotive-businesses-using-follow-up-crm': howToFixLeadResponseTimeInAutomotiveBusinessesUsingCrmAutomation,
  'hvac-crm-pipeline-for-service-companies': hvacCrmPipelineForServiceCompanies,
  'hvac-emergency-call-handling-mistakes': hvacEmergencyCallHandlingMistakes,
  'hvac-local-visibility-system-for-service-areas': hvacLocalVisibilitySystemForServiceAreas,
  'hvac-review-generation-framework': hvacReviewGenerationFramework,
  'lead-automation-framework-for-service-businesses': leadAutomationFrameworkForServiceBusinesses,
  'lead-qualification-for-roofing-companies': leadQualificationForRoofingCompanies,
  'lead-qualification-framework-for-service-businesses': leadQualificationFrameworkForServiceBusinesses,
  'lead-response-time-for-service-businesses': leadResponseTimeForServiceBusinesses,
  'lead-routing-for-hvac-companies': leadRoutingForHvacCompanies,
  'lead-routing-models-for-service-companies': leadRoutingModelsForServiceCompanies,
  'local-seo-for-roofing-companies-explained': localSeoForRoofingCompaniesExplained,
  'local-seo-vs-website-optimization': localSeoVsWebsiteOptimization,
  'local-service-page-architecture-for-local-businesses': localServicePageArchitectureForLocalBusinesses,
  'local-service-page-architecture-for-roofing-companies': localServicePageArchitectureForRoofingCompanies,
  'local-visibility-framework-for-service-businesses': localVisibilityFrameworkForServiceBusinesses,
  'missed-call-recovery-for-service-businesses': missedCallRecoveryForServiceBusinesses,
  'multi-channel-lead-capture-for-salons': multiChannelLeadCaptureForSalons,
  'multi-channel-lead-capture-system-for-service-businesses': multiChannelLeadCaptureSystemForServiceBusinesses,
  'negative-reviews-for-auto-repair-shops': negativeReviewsForAutoRepairShops,
  'plumbing-crm-pipeline-for-job-management': plumbingCrmPipelineForJobManagement,
  'realtor-local-visibility-system-for-lead-generation': realtorLocalVisibilitySystemForLeadGeneration,
  'reducing-salon-no-shows-with-automation': reducingSalonNoShowsWithAutomation,
  'reputation-monitoring-systems-for-service-businesses': reputationMonitoringSystemsForServiceBusinesses,
  'responding-to-negative-reviews-systematically': respondingToNegativeReviewsSystematically,
  'revenue-visibility-for-roofing-companies': revenueVisibilityForRoofingCompanies,
  'review-automation-for-hvac-companies': reviewAutomationForHvacCompanies,
  'review-automation-for-roofing-companies': reviewAutomationForRoofingCompanies,
  'review-automation-for-salons': reviewAutomationForSalons,
  'review-generation-system-for-local-businesses': reviewGenerationSystemForLocalBusinesses,
  'roofing-crm-pipeline-for-estimates': roofingCrmPipelineForEstimates,
  'roofing-estimate-follow-up-delays': roofingEstimateFollowUpDelays,
  'roofing-review-generation-system': roofingReviewGenerationSystem,
  'sales-pipeline-visibility-for-hvac-companies': salesPipelineVisibilityForHvacCompanies,
  'sales-pipeline-visibility-framework': salesPipelineVisibilityFramework,
  'salon-crm-pipeline-for-client-retention': salonCrmPipelineForClientRetention,
  'salon-review-generation-framework': salonReviewGenerationFramework,
  'service-business-follow-up-automation': serviceBusinessFollowUpAutomation,
  'service-page-architecture-for-service-businesses': servicePageArchitectureForServiceBusinesses,
  'smart-website-systems-for-roofing-companies': smartWebsiteSystemsForRoofingCompanies,
  'systems-first-website-for-hvac-companies': systemsFirstWebsiteForHvacCompanies,
  'tracking-customer-lifetime-value-using-crm': trackingCustomerLifetimeValueUsingCrm,
  'tracking-salon-client-lifetime-value': trackingSalonClientLifetimeValue,
  'website-crm-integration-for-salons': websiteCrmIntegrationForSalons,
  'website-crm-integration-for-service-businesses': websiteCrmIntegrationForServiceBusinesses,
  'website-design-that-supports-crm-systems': websiteDesignThatSupportsCrmSystems,
  'what-is-a-systems-first-website-for-service-businesses': whatIsASystemsFirstWebsiteForServiceBusinesses,
  'why-auto-repair-missed-calls-lose-booked-work': whyAutoRepairMissedCallsLoseBookedWork,
  'why-auto-repair-shops-lose-phone-leads': whyAutoRepairShopsLosePhoneLeads,
  'why-booking-systems-need-website-infrastructure': whyBookingSystemsNeedWebsiteInfrastructure,
  'why-hvac-companies-disappear-from-local-search': whyHvacCompaniesDisappearFromLocalSearch,
  'why-hvac-companies-lose-leads-after-hours': whyHvacCompaniesLoseLeadsAfterHours,
  'why-hvac-missed-calls-lose-after-hours-revenue': whyHvacMissedCallsLoseAfterHoursRevenue,
  'why-plumbing-companies-lose-jobs-without-crm-pipeline': whyPlumbingCompaniesLoseJobsWithoutCrmPipeline,
  'why-realtors-lose-leads-without-local-visibility': whyRealtorsLoseLeadsWithoutLocalVisibility,
  'why-roofing-companies-lose-jobs-without-review-automation': whyRoofingCompaniesLoseJobsWithoutReviewAutomation,
  'why-roofing-companies-lose-leads-during-storm-season': whyRoofingCompaniesLoseLeadsDuringStormSeason,
  'why-roofing-missed-calls-cost-emergency-jobs': whyRoofingMissedCallsCostEmergencyJobs,
  'why-salons-lose-calls-during-service-hours': whySalonsLoseCallsDuringServiceHours,
  'why-salons-lose-clients-without-crm-pipeline': whySalonsLoseClientsWithoutCrmPipeline,
  'why-salons-lose-clients-without-review-automation': whySalonsLoseClientsWithoutReviewAutomation,
  'why-salons-need-lead-handling-systems': whySalonsNeedLeadHandlingSystems,
  'why-service-business-websites-fail-to-convert': whyServiceBusinessWebsitesFailToConvert,
  'why-slow-lead-response-is-killing-automotive-businesses': whySlowLeadResponseIsKillingAutomotiveBusinesses,
  'why-slow-lead-response-is-killing-hvac-businesses': whySlowLeadResponseIsKillingHvacBusinesses,
};

export const blogPosts = Object.values(BLOG_POSTS);
