// AUTO-GENERATED by scripts/generate-content-registries.mjs. Do not edit manually.
import { authoritySignalsForLocalSearch } from '@/domains/resources/content/AuthoritySignalsForLocalSearch';
import { autoRepairLeadHandlingExample } from '@/domains/resources/content/AutoRepairLeadHandlingExample';
import { autoReplyFunnel } from '@/domains/resources/content/AutoReplyFunnel';
import { automotiveCrmPipelineForRepairJobs } from '@/domains/resources/content/AutomotiveCrmPipelineForRepairJobs';
import { automotiveReviewGenerationSystem } from '@/domains/resources/content/AutomotiveReviewGenerationSystem';
import { automotiveServiceReminderAutomation } from '@/domains/resources/content/AutomotiveServiceReminderAutomation';
import { bookingSystemsInsideWebsiteInfrastructure } from '@/domains/resources/content/BookingSystemsInsideWebsiteInfrastructure';
import { buildingRevenueVisibilityThroughCrmTracking } from '@/domains/resources/content/BuildingRevenueVisibilityThroughCrmTracking';
import { clientReactivationSystems } from '@/domains/resources/content/ClientReactivationSystems';
import { conversionArchitectureForServiceWebsites } from '@/domains/resources/content/ConversionArchitectureForServiceWebsites';
import { conversionTrackingForServiceBusinesses } from '@/domains/resources/content/ConversionTrackingForServiceBusinesses';
import { crmPipelineArchitecture } from '@/domains/resources/content/CrmPipelineArchitecture';
import { crmPipelineAutomation } from '@/domains/resources/content/CrmPipelineAutomation';
import { crmPipelineSetupGuideForPlumbingBusinesses } from '@/domains/resources/content/CrmPipelineSetupGuideForPlumbingBusinesses';
import { crmPipelineSetupGuideForSalons } from '@/domains/resources/content/CrmPipelineSetupGuideForSalons';
import { customerFeedbackLoopFramework } from '@/domains/resources/content/CustomerFeedbackLoopFramework';
import { designingWebsitesThatSupportCrmSystems } from '@/domains/resources/content/DesigningWebsitesThatSupportCrmSystems';
import { googleBusinessProfileSystemArchitecture } from '@/domains/resources/content/GoogleBusinessProfileSystemArchitecture';
import { howReviewAutomationImprovesLocalAuthority } from '@/domains/resources/content/HowReviewAutomationImprovesLocalAuthority';
import { howSmartWebsiteSystemsWork } from '@/domains/resources/content/HowSmartWebsiteSystemsWork';
import { hvacCrmPipelineStructure } from '@/domains/resources/content/HvacCrmPipelineStructure';
import { hvacEmergencyCallHandlingSystem } from '@/domains/resources/content/HvacEmergencyCallHandlingSystem';
import { hvacLeadHandlingExample } from '@/domains/resources/content/HvacLeadHandlingExample';
import { hvacReviewGenerationFramework } from '@/domains/resources/content/HvacReviewGenerationFramework';
import { leadAutomationFramework } from '@/domains/resources/content/LeadAutomationFramework';
import { leadQualificationFramework } from '@/domains/resources/content/LeadQualificationFramework';
import { leadResponseOptimizationChecklistForHvacBusinesses } from '@/domains/resources/content/LeadResponseOptimizationChecklistForHvacBusinesses';
import { leadResponseTimeFramework } from '@/domains/resources/content/LeadResponseTimeFramework';
import { leadRoutingModelsForServiceCompanies } from '@/domains/resources/content/LeadRoutingModelsForServiceCompanies';
import { localSeoVsWebsiteOptimization } from '@/domains/resources/content/LocalSeoVsWebsiteOptimization';
import { localServicePageArchitecture } from '@/domains/resources/content/LocalServicePageArchitecture';
import { localVisibilityFramework } from '@/domains/resources/content/LocalVisibilityFramework';
import { localVisibilityOptimizationGuideForHvacCompanies } from '@/domains/resources/content/LocalVisibilityOptimizationGuideForHvacCompanies';
import { localVisibilityOptimizationGuideForRealtors } from '@/domains/resources/content/LocalVisibilityOptimizationGuideForRealtors';
import { missedCallRecoveryForAutoRepair } from '@/domains/resources/content/MissedCallRecoveryForAutoRepair';
import { missedCallRecoveryForHvac } from '@/domains/resources/content/MissedCallRecoveryForHvac';
import { missedCallRecoveryForRoofing } from '@/domains/resources/content/MissedCallRecoveryForRoofing';
import { missedCallRecoveryForSalons } from '@/domains/resources/content/MissedCallRecoveryForSalons';
import { missedCallRecoverySystem } from '@/domains/resources/content/MissedCallRecoverySystem';
import { multiChannelLeadCaptureSystems } from '@/domains/resources/content/MultiChannelLeadCaptureSystems';
import { reducingSalonNoShowsWithAutomation } from '@/domains/resources/content/ReducingSalonNoShowsWithAutomation';
import { reputationMonitoringSystems } from '@/domains/resources/content/ReputationMonitoringSystems';
import { respondingToNegativeReviewsSystematically } from '@/domains/resources/content/RespondingToNegativeReviewsSystematically';
import { reviewAutomationSetupGuideForRoofingCompanies } from '@/domains/resources/content/ReviewAutomationSetupGuideForRoofingCompanies';
import { reviewAutomationSetupGuideForSalons } from '@/domains/resources/content/ReviewAutomationSetupGuideForSalons';
import { reviewGenerationSystem } from '@/domains/resources/content/ReviewGenerationSystem';
import { roofingCrmPipelineStructure } from '@/domains/resources/content/RoofingCrmPipelineStructure';
import { roofingEstimateFollowUpWorkflow } from '@/domains/resources/content/RoofingEstimateFollowUpWorkflow';
import { roofingLeadHandlingExample } from '@/domains/resources/content/RoofingLeadHandlingExample';
import { roofingReviewGenerationSystem } from '@/domains/resources/content/RoofingReviewGenerationSystem';
import { salesPipelineVisibilityFramework } from '@/domains/resources/content/SalesPipelineVisibilityFramework';
import { salonLeadHandlingExample } from '@/domains/resources/content/SalonLeadHandlingExample';
import { salonReviewGenerationFramework } from '@/domains/resources/content/SalonReviewGenerationFramework';
import { serviceBusinessFollowUpAutomationGuide } from '@/domains/resources/content/ServiceBusinessFollowUpAutomationGuide';
import { servicePageArchitectureThatConverts } from '@/domains/resources/content/ServicePageArchitectureThatConverts';
import { trackingCustomerLifetimeValueUsingCrm } from '@/domains/resources/content/TrackingCustomerLifetimeValueUsingCrm';
import { trackingSalonClientLifetimeValue } from '@/domains/resources/content/TrackingSalonClientLifetimeValue';
import { websiteCrmIntegrationExplained } from '@/domains/resources/content/WebsiteCrmIntegrationExplained';
import { whatIsASystemsFirstWebsite } from '@/domains/resources/content/WhatIsASystemsFirstWebsite';
import type { ResourceData } from '@/domains/resources/types';

export const RESOURCE_REGISTRY: Record<string, ResourceData> = {
  'authority-signals-for-local-search': authoritySignalsForLocalSearch,
  'auto-repair-lead-handling-example': autoRepairLeadHandlingExample,
  'auto-reply-funnel': autoReplyFunnel,
  'automotive-crm-pipeline-for-repair-jobs': automotiveCrmPipelineForRepairJobs,
  'automotive-review-generation-system': automotiveReviewGenerationSystem,
  'automotive-service-reminder-automation': automotiveServiceReminderAutomation,
  'booking-systems-inside-website-infrastructure': bookingSystemsInsideWebsiteInfrastructure,
  'building-revenue-visibility-through-crm-tracking': buildingRevenueVisibilityThroughCrmTracking,
  'client-reactivation-systems': clientReactivationSystems,
  'conversion-architecture-for-service-websites': conversionArchitectureForServiceWebsites,
  'conversion-tracking-for-service-businesses': conversionTrackingForServiceBusinesses,
  'crm-pipeline-architecture': crmPipelineArchitecture,
  'crm-pipeline-automation': crmPipelineAutomation,
  'crm-pipeline-setup-guide-for-plumbing-businesses': crmPipelineSetupGuideForPlumbingBusinesses,
  'crm-pipeline-setup-guide-for-salons': crmPipelineSetupGuideForSalons,
  'customer-feedback-loop-framework': customerFeedbackLoopFramework,
  'designing-websites-that-support-crm-systems': designingWebsitesThatSupportCrmSystems,
  'google-business-profile-system-architecture': googleBusinessProfileSystemArchitecture,
  'how-review-automation-improves-local-authority': howReviewAutomationImprovesLocalAuthority,
  'how-smart-website-systems-work': howSmartWebsiteSystemsWork,
  'hvac-crm-pipeline-structure': hvacCrmPipelineStructure,
  'hvac-emergency-call-handling-system': hvacEmergencyCallHandlingSystem,
  'hvac-lead-handling-example': hvacLeadHandlingExample,
  'hvac-review-generation-framework': hvacReviewGenerationFramework,
  'lead-automation-framework': leadAutomationFramework,
  'lead-qualification-framework': leadQualificationFramework,
  'lead-response-optimization-checklist-for-hvac-businesses': leadResponseOptimizationChecklistForHvacBusinesses,
  'lead-response-time-framework': leadResponseTimeFramework,
  'lead-routing-models-for-service-companies': leadRoutingModelsForServiceCompanies,
  'local-seo-vs-website-optimization': localSeoVsWebsiteOptimization,
  'local-service-page-architecture': localServicePageArchitecture,
  'local-visibility-framework': localVisibilityFramework,
  'local-visibility-optimization-guide-for-hvac-companies': localVisibilityOptimizationGuideForHvacCompanies,
  'local-visibility-optimization-guide-for-realtors': localVisibilityOptimizationGuideForRealtors,
  'missed-call-recovery-for-auto-repair': missedCallRecoveryForAutoRepair,
  'missed-call-recovery-for-hvac': missedCallRecoveryForHvac,
  'missed-call-recovery-for-roofing': missedCallRecoveryForRoofing,
  'missed-call-recovery-for-salons': missedCallRecoveryForSalons,
  'missed-call-recovery-system': missedCallRecoverySystem,
  'multi-channel-lead-capture-systems': multiChannelLeadCaptureSystems,
  'reducing-salon-no-shows-with-automation': reducingSalonNoShowsWithAutomation,
  'reputation-monitoring-systems': reputationMonitoringSystems,
  'responding-to-negative-reviews-systematically': respondingToNegativeReviewsSystematically,
  'review-automation-setup-guide-for-roofing-companies': reviewAutomationSetupGuideForRoofingCompanies,
  'review-automation-setup-guide-for-salons': reviewAutomationSetupGuideForSalons,
  'review-generation-system': reviewGenerationSystem,
  'roofing-crm-pipeline-structure': roofingCrmPipelineStructure,
  'roofing-estimate-follow-up-workflow': roofingEstimateFollowUpWorkflow,
  'roofing-lead-handling-example': roofingLeadHandlingExample,
  'roofing-review-generation-system': roofingReviewGenerationSystem,
  'sales-pipeline-visibility-framework': salesPipelineVisibilityFramework,
  'salon-lead-handling-example': salonLeadHandlingExample,
  'salon-review-generation-framework': salonReviewGenerationFramework,
  'service-business-follow-up-automation-guide': serviceBusinessFollowUpAutomationGuide,
  'service-page-architecture-that-converts': servicePageArchitectureThatConverts,
  'tracking-customer-lifetime-value-using-crm': trackingCustomerLifetimeValueUsingCrm,
  'tracking-salon-client-lifetime-value': trackingSalonClientLifetimeValue,
  'website-crm-integration-explained': websiteCrmIntegrationExplained,
  'what-is-a-systems-first-website': whatIsASystemsFirstWebsite,
};

export const resources = Object.values(RESOURCE_REGISTRY);
